language: node_js
notifications:
  email:
    recipients:
      - 461354294@qq.com
    on_success: change # default: change
    on_failure: always # default: always
before_install:
  - npm install
script:
  - node index.js